### ISSUE TITLE
Use new project

### ISSUE THREAD

**Issue by Weredime** [Looky1173/Scratch-Auth-Server#1]
Without telling the community, change the project id to something random like https://scratch.mit.edu/projects/519766755/  and remove the banner on client

**Comment by Weredime** [comment]
This type is used everywhere for discord bots, etc.

**Comment by Looky1173** [comment]
@Weredime I think this would cause the ban hammer to strike me hard, don't you think?

**Comment by Looky1173** [comment]
@Weredime Also please see [this post by me](https://scratch.mit.edu/discuss/topic/446450/?page=162#post-6366556).

**Comment by Weredime** [comment]
> @Weredime I think this would cause the ban hammer to strike me hard, don't you think?

I guess its last resort time to make the better scratch ig

**Comment by Looky1173** [comment]
I will close this for now because authentication with profile comments is now possible.
