### ISSUE TITLE
Feature Request: Custom projects

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Server#2]
It'd be nice to have the ability to make your own authentication project. This would allow for project authentication to work, and would allow for extra customization. This could likely be done in a similar way to [my fork](/steve0greatness/Scratch-Auth-Server), but I wouldn't recommend merging it directly from there as I wasn't able to test it.

# Method of Doing This
This is the method that I used, but there may or may not be some other ones. First in `routes/auth/generateTokens.js` I made it so that it either saves the authProject as `req.query.authProject` or if it's not there, only then, is it saved as `AUTH_POJECT.id`. Under the same directory in `verifyToken.js` I made it send some data for cloud and comment verification, that data was the authentication project id set in `generateTokens.js`. From there, in `lib/queue.js` I simply changed the cloud data endpoint to use the data send instead of the constant; same in the comment endpoint, I just also made the author a variable that will be set to `AUTH_PROJECT.author` by default, but if the sent data isn't the same as `AUTH_PROJECT.id` then it gets the then it requests the project by the id of the sent data and grabs the author from there, then the author constant there is changed to the author variable.

That's an explanation of the changes in my fork, and the method I used for this. However, it may slow down the whole thing just a bit, as it will have to request the author of the project. It may be better to request the author of the project before it goes into the queue.

**Comment by Looky1173** [comment]
@Steve0Greatness Thanks for the PR! I will implement this as soon as possible and I will notify you here.

**Comment by Looky1173** [comment]
@Steve0Greatness Implemented in 20e3d693cc87ecca777712ba7661dffe56c249e4 and Looky1173/Scratch-Auth-Client@596c1d0998519639ba804c31fba8699e67a4160e, closing.
