### ISSUE TITLE
Set the 'Access-Control-Allow-Origin' to * on every request.

### ISSUE THREAD

**Issue by Steve0Greatness** [Looky1173/Scratch-Auth-Server#3]
Hello! I'm currently working on implementing a custom frontend for Scratch Auth in [PenguinMod](https://github.com/PenguinMod/PenguinMod-Home), they do their auth almost entirely with the frontend, this means that these APIs need to be called with the frontend, which cannot happend unless these are set to allow CORS.

**Comment by Looky1173** [comment]
Hi, `Access-Control-Allow-Origin` should [already](https://github.com/Looky1173/Scratch-Auth-Server/blob/d80407a8cb2578a693efeaa764940864fb9a56a0/index.js#L34-L38) be set to `*` for every request.

**Comment by Steve0Greatness** [comment]
Thanks for the response, however, when I use the API, the headers I get sent back are:

```
HTTP/2 200 
age: 0
cache-control: public, max-age=0, must-revalidate
content-type: application/json; charset=utf-8
date: Sat, 18 Nov 2023 17:41:49 GMT
etag: "10a-Tc/a7jfk1c/vGU5oV1xmwWR6JSk"
server: Vercel
strict-transport-security: max-age=63072000
x-matched-path: /api/auth/getTokens
x-vercel-cache: MISS
x-vercel-id: sfo1::iad1::xhxgt-1700329309623-490cb9e3bdae
content-length: 266
X-Firefox-Spdy: h2
```

Is using the `https://auth.itinerary.eu.org/api/auth/*` endpoints for this API incorrect? I'm asking since when I use `https://scratch-auth-server.vercel.app/*`, these headers do appear.

**Comment by Looky1173** [comment]
Ah, `https://auth.itinerary.eu.org/api/auth/*` is meant for internal use by `https://auth.itinerary.eu.org/`. Please use the following instead: <pre>https://<b>auth-api</b>.itinerary.eu.org/auth/*</pre>

![image](https://github.com/Looky1173/Scratch-Auth-Server/assets/60521810/500197a7-0193-49f6-b903-171f0c9c5de2)
